version: 1.0

services:
  client:
    type: web
    env: docker
    buildCommand: docker build -t client ./client
    startCommand: docker run -p 3000:80 -e REACT_APP_API_URL=http://localhost:5000 client
    dockerfilePath: ./client/Dockerfile
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: http://localhost:5000

  server:
    type: web
    env: docker
    buildCommand: docker build -t server ./server
    startCommand: docker run -p 5000:5000 -e PG_USER=postgres -e PG_HOST=postgres -e PG_PORT=5432 -e PG_DATABASE=tasklist -e SESS_SECRET=your_session_secret server
    dockerfilePath: ./server/Dockerfile
    autoDeploy: true
    envVars:
      - key: PG_USER
        value: postgres
      - key: PG_HOST
        value: postgres
      - key: PG_PORT
        value: "5432"
      - key: PG_DATABASE
        value: tasklist
      - key: SESS_SECRET
        value: your_session_secret

  postgres:
    type: database
    env: postgres
    buildCommand: docker build -t postgres ./db
    startCommand: docker run -e POSTGRES_PASSWORD=mysecretpassword -v postgres-data:/var/lib/postgresql/data postgres
    dockerfilePath: ./db/Dockerfile
    autoDeploy: true
    envVars:
      - key: POSTGRES_PASSWORD
        value: mysecretpassword

volumes:
  postgres-data: {}