# Get folders

GET http://localhost:5000/folders

###

# Add new folder
POST http://localhost:5000/folders
Content-Type: application/json

{
    "folderName": "TEST FOLDER",
    "colorId": "1"
}

###

# Update folder
PUT http://localhost:5000/folders/240
Content-Type: application/json

{
    "folderName": "TEST FOLDER NEW",
    "colorId": "2"
}

###


# Delete folder
DELETE http://localhost:5000/folders/240

